// author: uniqs
// uniqs@163.com
// ====================== This file is generated by uniqs, don't change it!!!!!! ====================== 



#include "CfgTables.h"

#include "DTtest.h"

std::unique_ptr<DTCfgTable<int, DTtest>> g_pCfg_test = nullptr;

bool LoadDTTables_test(const char* szFile, std::string& err)
{
	if (!g_pCfg_test)
	{
		g_pCfg_test = std::make_unique<DTCfgTable<int, DTtest>>();
	}

	if (!g_pCfg_test->Load(szFile, err)) return false;

	return true;
}

bool LoadDTTables(const std::string& prefix, std::string& err)
{
	std::string file;

	file = prefix + "DTtest.json";
	if (!LoadDTTables_test(file.c_str(), err)) return false;

	return true;
}
