// author: uniqs
// uniqs@163.com
// ====================== This file is generated by uniqs, don't change it!!!!!! ====================== 



#include "CfgTables.h"

#include "DTtest.h"

std::unique_ptr<DTCfgTable<int, DTtest>> g_pCfg_test = nullptr;

bool LoadDTTables_test(const char* szFile, std::string& err)
{
	Json::Value jvalue;
	if (!ReadJson(jvalue, szFile, err)) return false;

	if (!g_pCfg_test)
	{
		g_pCfg_test = std::make_unique<DTCfgTable<int, DTtest>>();
	}

	if (!g_pCfg_test->LoadDT(jvalue)) return false;

	return true;
}

void LoadDTTables()
{
	LoadDTTables_test("./TableJson/DTtest.json");
}
